name: Update README

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  name: Update this repo's README with recent activity
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}